name: Xave
favicon: null
layout_spectrum: 0.22868
typography_spectrum: 0.50543
title: Smile at Xave
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#5a6521'
    - '#ffd8c4'
    - '#bac22f'
    - '#6f99b1'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
